### ISSUE TITLE
Configure the IVNS

### ISSUE THREAD

**Issue by roSimoes** [PhilippMundhenk/IVNS#1]
Hello, first of all I would like to congratulate you for this excellent project.

I'm putting together a system with several ECUs to be able to read the CAN messages and intrude a malicious agent, in order to generate a dataset to later train a Neuronal network.

However I am not able to start the project after installing eclipse and installing python 2.7 I have the following error:

Traceback (most recent call last):
  File "/home/rodolfo/eclipse-workspace/IVNS/IVNS-master/TestSimulation/main_tesla_preset.py", line 16, in <module>
    from api.core.api_core import TimingFunctionSet
ImportError: No module named api.core.api_core

Could you give me some help?

best regards

**Comment by arturmrowca** [comment]
Am Di., 19. März 2019 um 15:23 Uhr schrieb roSimoes <
notifications@github.com>:

**Comment by arturmrowca** [comment]
Hello,

this error looks as if the Main simulation project ECUSimulation was not imported properly. You can either import the ECUSimulation project into the TestSimulation project by using Eclipse or an easier solution is to simply add: 

import sys

sys.path.append("../ECUSimulation")
sys.path.append("../ECUInteraction")
sys.path.append("../Testcases")

to the top of the main_tesla_preset.py file. 
Actually you are right, that this should be in the repository. I will adjust it directly. 

Please also checkout the wiki: https://github.com/arturmrowca/IVNS/wiki/
Also note that the project is further continued in https://github.com/arturmrowca/IVNS/

Did that work? Else let me know and we will find a solution to your problem.

Using our simulator for intrusion detection is a great idea. The simulator should provide all the capabilities you require. If you need assistance with setting up the communication or anything I am happy to help you. If you give me some more specifics I can also write a short example for you which helps you to use our simulator for this task. 

Thanks for using our simulator. 
Best. 
Artur
